name: Weather Telegram Bot

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:
    inputs:
      manual_request:
        description: "Manual request from Telegram"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run weather bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MANUAL_REQUEST: ${{ github.event.inputs.manual_request || 'false' }}
        run: |
          python weather_bot.py

      - name: Save weather state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add state.json

          if git diff --cached --quiet; then
            echo "No state changes."
          else
            git commit -m "Update weather state"
            git push
          fi
